package com.joprelys.backend.spatial.infrastructure.persistence;

public enum BedStateReasonCode {
    CAPACITY_REOPENING,
    CAPACITY_TEMPORARY_CLOSURE,
    CAPACITY_STAFFING_SHORTAGE,
    CAPACITY_SAFETY,
    CAPACITY_OTHER,
    CLEANING_AFTER_DEPARTURE,
    CLEANING_AFTER_TRANSFER,
    CLEANING_ROUTINE,
    CLEANING_ISOLATION,
    CLEANING_INCIDENT,
    CLEANING_COMPLETED,
    MAINTENANCE_PREVENTIVE,
    MAINTENANCE_CORRECTIVE,
    MAINTENANCE_SAFETY,
    MAINTENANCE_COMPLETED,
    LEGACY_SUPERVISION
}
